// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTqpkef2GD3XVDza0visZfYpF1Sos-AS8',
    appId: '1:162701310583:web:e8ff353eaab29b57a56472',
    messagingSenderId: '162701310583',
    projectId: 'shoppad-f3d43',
    authDomain: 'shoppad-f3d43.firebaseapp.com',
    databaseURL: 'https://shoppad-f3d43-default-rtdb.firebaseio.com',
    storageBucket: 'shoppad-f3d43.firebasestorage.app',
    measurementId: 'G-PG3X76XSSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuilJCNKxld6HurEnQ0iz1kJMffyR4nBk',
    appId: '1:162701310583:android:8d5d155b99639d64a56472',
    messagingSenderId: '162701310583',
    projectId: 'shoppad-f3d43',
    databaseURL: 'https://shoppad-f3d43-default-rtdb.firebaseio.com',
    storageBucket: 'shoppad-f3d43.firebasestorage.app',
  );
}
